openapi: 3.1.0
info:
  title: API Documentaci贸n con OpenAPI
  description: Documentaci贸n de la API de planetas y personas.
  version: 1.1.1
  license:
    name: MIT
    url: "https://opensource.org/license/mit/"

servers:
  - url: "https://kk0r6gi4ua.execute-api.us-east-1.amazonaws.com"

paths:
  /people/{id}:
    $ref: people\people.yaml
  /planets:
    $ref: planets\planets.yaml

tags:
  - name: Planets
    description: Gesti贸n de planetas
  - name: People
    description: Integraci贸n con SWAPI

security: 
  []  # No se requiere seguridad
